name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build and run:
    name: Build and Run

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      run: make build
    - name: Run Code
      run: make run
    - name: Clean
      run: make clean
